### ISSUE TITLE
Add validation GHA workflow for all maps

### ISSUE THREAD

**Issue by ronaldtse** [interscript/maps#15]
We want to validate that the map filenames are correctly named according to the metadata of the system.

e.g. `alalc-jap-Hrkt-Latn-foobar.imp` needs to have the segments checked:
* Does `alalc` exist as an authority and specified in the file?
* Is `jap` specified in the file and belongs to `iso-639-2:jap` => is a valid code in ISO 639-2?
* does `Hrkt` and `Latn` belong to ISO 15924?
* Is `foobar` set as the `id: foobar` inside the file?

**Comment by webdev778** [comment]
Already Fixed
