### ISSUE TITLE
Implement system `az-aze-cyrl-latn-1991` (Azerbijian Government -- Alphabet Transition from Cyrillic to Latin

### ISSUE THREAD

**Issue by ronaldtse** [interscript/maps#154]
This issue is to implement the transliteration system of az-aze-cyrl-latn-1991.

This system is referred in the GeoNames database as `aze_Cyrl2Latn_GAZ_1991`, with the system title 'Azerbijian Government -- Alphabet Transition from Cyrillic to Latin'.

 Tests should rely on the data extracted for the `aze_Cyrl2Latn_GAZ_1991` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by CAMOBAP** [comment]
> I believe this is the system mentioned here: https://www.rferl.org/a/1097070.html
> 
> The government system that converts Cyrillic to Latin in 1991.
> 
> > One of the first acts of legislation voted by Azerbaijan's parliament after the demise of the Soviet Union in 1991 was to adopt a Latin script to replace the Cyrillic alphabet forcibly imposed on the country by Soviet leader Joseph Stalin.

So it's about `replacement` as noted before and not about new transliteration rules. If there is a such document it will be Arab-Latn but not `Cyrl-Latn`

1939/1958 was about transliteration from Cyrillic alphabet to Latin
1991 was about developing new Latin alphabet not about transliteration

> Seems to provide the alphabet but not the mapping. It is possible to infer the mapping by linking the IPA symbols with Cyrillic and Latin.

But this will make no sense. It will not represent any existing transliteration mapping/rules but will create a new one and our own mapping

I propose to close this one
